name: Build Test with `-DDEBUG` - CentOS7

on:
  push:
    branches: [ OVIS-4 ]
  pull_request:
    branches: [ OVIS-4 ]

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
        image: ovishpc/ovis-centos-build:latest
    steps:
    - uses: actions/checkout@v3
    - run: sh autogen.sh
    - run: |
        _CFLAGS_=(
          -DDEBUG -DEP_DEBUG -DCTXT_DEBUG -DPUSH_DEBUG -DLOADAVG_CONFIG_DEBUG
          -DLOADAVG_TYPE_DEBUG -DSEND_RECV_DEBUG -DZAP_DEBUG -DDEBUG_ZAP_SOCK
          -DTMP_DEBUG -DZAP_UGNI_DEBUG
        )
        _ENABLES_=(
          --enable-zaptest
          --enable-ldms-test
          --enable-rdma
          --enable-fabric
          --with-libfabric=/usr
        )
        ./configure ${_ENABLES_[*]} CFLAGS="${_CFLAGS_[*]}"
    - run: make
