name: Create Release

on:
  push:
    tags:
      - 'OVIS-4*'

jobs:
  build:
    name: Create Release
    # Make sure that test-make-dist.yaml has the same "runs-on" and
    # "container" as used here.
    runs-on: ubuntu-20.04
    container:
        image: ovishpc/ovis-ubuntu-build

    steps:
    - uses: actions/checkout@v2
    # actions/checkout@v2 breaks annotated tags by converting them into
    # lightweight tags, so we need to force fetch the tag again
    # See: https://github.com/actions/checkout/issues/290
    - name: Repair tag
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
    - name: Verify tag is annotated
      run: if test x$(git for-each-ref ${{ github.ref }} | awk '{print $2}') = xtag; then /bin/true; else echo "\"${{ github.ref }}\" does not look like an annotated tag!"; /bin/false; fi
    - name: autogen.sh
      run: sh autogen.sh
    - name: configure
      run: ./configure
    - name: make dist
      run: |
        make dist
        echo TARBALL_NAME=$(ls *.tar.gz | head -1) >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a pload_url See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./${{ env.TARBALL_NAME }}
        asset_name: ${{ env.TARBALL_NAME }}
        asset_content_type: application/gzip
    - name: Upload TOSS Spec File
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rpm/ovis-ldms-toss3.spec
        asset_name: ovis-ldms-toss3.spec
        asset_content_type: text/plain
    - name: Upload TOSS Spec File
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rpm/ovis-ldms-toss4.spec
        asset_name: ovis-ldms-toss4.spec
        asset_content_type: text/plain
